// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCagyHbsMHJOmZ97WymG1v1hLO3y1Y9pg',
    appId: '1:147947085523:web:368fff68211843b253fe26',
    messagingSenderId: '147947085523',
    projectId: 'later-b3ead',
    authDomain: 'later-b3ead.firebaseapp.com',
    storageBucket: 'later-b3ead.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwAsMZuvucu094_tq0dYuT6AM2vSWEcHI',
    appId: '1:147947085523:android:1fcc8ddcc968f5b153fe26',
    messagingSenderId: '147947085523',
    projectId: 'later-b3ead',
    storageBucket: 'later-b3ead.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD655XohcMY5rNlR_Yk2dqyP8SXGZuvGvQ',
    appId: '1:147947085523:ios:d378fa365384ed7f53fe26',
    messagingSenderId: '147947085523',
    projectId: 'later-b3ead',
    storageBucket: 'later-b3ead.appspot.com',
    iosClientId: '147947085523-tq7c2anlmdc6pofqv5knq17sbktm4api.apps.googleusercontent.com',
    iosBundleId: 'dev.petersalmon.later',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD655XohcMY5rNlR_Yk2dqyP8SXGZuvGvQ',
    appId: '1:147947085523:ios:d378fa365384ed7f53fe26',
    messagingSenderId: '147947085523',
    projectId: 'later-b3ead',
    storageBucket: 'later-b3ead.appspot.com',
    iosClientId: '147947085523-tq7c2anlmdc6pofqv5knq17sbktm4api.apps.googleusercontent.com',
    iosBundleId: 'dev.petersalmon.later',
  );
}
